// Generated by scripts/generate-ios-integrity-manifest.js. Do not edit manually.
import CryptoKit
import Foundation

enum RuntimeIntegrityManifest {
    private static let protectedFiles: [String: String] = [
        "public/cordova_plugins.js": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "public/cordova.js": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "public/css/modal.css": "5a52123feec537dba7197943c9289bbea836bfd03fd297d5ebba8b91c6109d3e",
        "public/css/player.css": "af0d2808d9ee2d12ae0464ac9b4d41c2f6814281e1cc4124a875a47aaffced97",
        "public/css/style.css": "fdeeec463d8381ed29d60a26e4592e764875fbab9428d158814a2fef9cd09add",
        "public/css/tv.css": "4ad38e4a9af9696fa99effd05e25e4bcfe05a5ea116b924dc467c71c5f43b192",
        "public/css/web-premium.css": "967e2e452f376c7a9f182b8cb53d6415959176102deb8fd79d274a6eb17c850b",
        "public/index.html": "58632e4907d854f261cba549f50a99cb811e4952de7ae0a20ab444d142756e73",
        "public/js/admin.js": "c231359a790688ffcc66c59209a49d1b7277cd885994d7aa3d9b6952b6e33237",
        "public/js/api.js": "a4e35818ade969be3759d60b6228a463a18abf904b2c5281d69e84ca6281350a",
        "public/js/app.js": "563452591f79d2d105c369e77fa2b7a9a1c4b7e073ef14332d320e99f5ad1561",
        "public/js/audio-enhancer.js": "5e4a54d0cfb9abe0c11b41f63cc96baecbd33b6c34c3228f5e15f9fe1f383915",
        "public/js/auth.js": "905e1186b9d760e7304b63b126d704edc4585e998d039184fde7f1a9100aecc8",
        "public/js/catalog-fallback.js": "8ab81d28b4295c052218cc508239a5f1a6736a425d6ec7d4ffb22582b08523a3",
        "public/js/coverflow.js": "710e129b187cbb7a0785c8ccaddc40f652dc2b56f4e25cd548d231adb2826b64",
        "public/js/diagnostics.js": "477a0d7ed75d8018800a3691fe360144758e1962eb1d7bf55c217e37391d99d7",
        "public/js/feedback.js": "1813edd0f571e0d19718be692e875976f17297d5845ed77e85fb2b22380e0f23",
        "public/js/home-curation.js": "09a4a59ed29045aa918615a5d107a8d84000cb0c16d878e4be9134678dfdd3e7",
        "public/js/mobile-config.js": "a1b0917a8ed58993be046606d23043b479353f15d3ea6bb9e3fc774b9b292ac1",
        "public/js/native-downloads.js": "961f0e9c23b4271d373db2e55015ebd272228cc699cfe771de0adcef6f658814",
        "public/js/platform.js": "6dfb516cd395d03f2199d4d881b219f4f626237084856f3335d9447c03842fcb",
        "public/js/player-core.js": "9f8750318082163793065a81830435cf8fcf2426228c9fafabce9bf33550821e",
        "public/js/player.js": "b85d3427e1e79ff88ecf0ab5ccf4741c8c96aa6552033d584f2a3723a3581c17",
        "public/js/release-copy.js": "d72075a12d7661c14b5929aebabe52d99923fdc161552b773db1f4988b73d1d6",
        "public/js/runtime-config.js": "f1a98e25a54728f26e6bce538c570d0eb397f64bca0eb3ac61b31eda62a77bb9",
        "public/js/session-vault.js": "44f7df4d6436153995c75cf54fe4c6eccb4c3a51815b0e6d24ebe35efae90707",
        "public/js/tv.js": "f292a93f903c5886548297f692fc543dc11285ade5226640baa1487d9c934221",
        "public/media/avengers_4k.jpg": "3a11f26e07395cd6e46150994ce7fb5791afe4e84e0dbdbaf15429a800f5b5a5",
        "public/media/killer_shop_4k.jpg": "cc85f3ae2bbab87c5c53d661b12b075e890705eb56bfb230d3f922ef07b500d6",
        "public/media/phim4k-avatar.png": "d642f4f713d22fb37651ecff7e47368ad03b79d8a9164732a2f2fef269e1e104",
        "public/media/poster-fallback.svg": "0dedb95cd60973a3677b66d330e80a20ece8c0752d6b2de178b5960bfd3a607f",
        "public/media/qa-original.webm": "e98b9406d173fda158bc11e7a63b6b020edb0411f6f4640877df6a1c50830b88",
        "public/media/spider_man_4k.jpg": "1e6356bf1dfce786b534026aa48e9776a77090599380881a982fa1eaba7f79b0",
        "public/media/superman_4k.jpg": "9339c63a766caa26647be0b64cacf0c95e3db29859ce4445b5e9db15a05ab7fe",
        "public/media/the_boys_4k.jpg": "572cb16dfb429292bb9fc690a0c5bfa28a8d688ed23588595e396b454067971a",
        "public/vendor/hls.min.js": "afcde07437ec84b072fe8782e772ceb5046eac751b2719f73ae0d83d763bc3f5",
        "public/web-index.html": "08ce933fb9a000bf50b396c4c35d54fe8a6c5ce063ed8df543b5a2108f53d53e",
    ]

    static func verify(in bundle: Bundle = .main) -> Bool {
        guard let resourceRoot = bundle.resourceURL else { return false }
        let publicRoot = resourceRoot.appendingPathComponent("public", isDirectory: true)
        guard let enumerator = FileManager.default.enumerator(
            at: publicRoot,
            includingPropertiesForKeys: [.isRegularFileKey],
            options: [.skipsHiddenFiles]
        ) else { return false }

        var actualFiles = Set<String>()
        for case let url as URL in enumerator {
            guard (try? url.resourceValues(forKeys: [.isRegularFileKey]).isRegularFile) == true else { continue }
            let prefix = publicRoot.path + "/"
            guard url.path.hasPrefix(prefix) else { return false }
            let relative = "public/" + String(url.path.dropFirst(prefix.count))
            if relative.hasSuffix(".map") { return false }
            actualFiles.insert(relative)
        }

        guard actualFiles == Set(protectedFiles.keys) else { return false }
        for (relative, expectedDigest) in protectedFiles {
            let url = resourceRoot.appendingPathComponent(relative, isDirectory: false)
            guard let data = try? Data(contentsOf: url, options: .mappedIfSafe) else { return false }
            let digest = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
            guard digest == expectedDigest else { return false }
        }
        return true
    }
}
