// Generated by scripts/generate-ios-integrity-manifest.js. Do not edit manually.
import CryptoKit
import Foundation

enum RuntimeIntegrityManifest {
    private static let protectedFiles: [String: String] = [
        "public/cordova_plugins.js": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "public/cordova.js": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "public/css/modal.css": "7ac523cb8944e8dbffa29dd03f49b4e9324668d840bf48af01f4083388df961f",
        "public/css/player.css": "89974425bcd873a8e17f3b5b73e8bd1849484fc50fa3b3b50a3debf3507822d9",
        "public/css/style.css": "dd8bb9860944293220a704b6ea99c3085527b9fb7cc3ccac21a20bfa43e14fe6",
        "public/css/tv.css": "4ad38e4a9af9696fa99effd05e25e4bcfe05a5ea116b924dc467c71c5f43b192",
        "public/index.html": "70ad6034d1c54f6ff89874d0bc84f82601ca8f11f2556a999b6057fad5f4a396",
        "public/js/admin.js": "0d6e5ebab795d0ca85fa6e3031e20d4eea3053e624fd2053225a37ef37677bac",
        "public/js/api.js": "d966c0d535906d7e7d3c44afa08881cc3b55807135fbb6d5f38a8afd72dd5344",
        "public/js/app.js": "dcce0cd4ec857568292ccca0e9cce4d90ef3a620e547243bca3a480857203420",
        "public/js/audio-enhancer.js": "5e4a54d0cfb9abe0c11b41f63cc96baecbd33b6c34c3228f5e15f9fe1f383915",
        "public/js/auth.js": "720c2d2a0621e18ca86cb0ba3f2f3da6b2c082c2f145d5e80ac7e6705fe8db1f",
        "public/js/catalog-fallback.js": "8ab81d28b4295c052218cc508239a5f1a6736a425d6ec7d4ffb22582b08523a3",
        "public/js/coverflow.js": "efb2c62d9473323ba8b404a3fade1cae7413193172a823c3b76eb2e4a64e54c5",
        "public/js/diagnostics.js": "13dc11ab3af488917aa14e8db0768527820f086e11c4c4de1d6450996c0a1b1f",
        "public/js/home-curation.js": "8e9a8112a8887fec3b50f225b589922a00684b0188605c5c8e5b8ba1828847f5",
        "public/js/mobile-config.js": "7385474483833079613a5ea72107732c329e541cd54a32666d9b7377dcc296b3",
        "public/js/native-downloads.js": "961f0e9c23b4271d373db2e55015ebd272228cc699cfe771de0adcef6f658814",
        "public/js/platform.js": "6dfb516cd395d03f2199d4d881b219f4f626237084856f3335d9447c03842fcb",
        "public/js/player-core.js": "725e30dccee3ac702956ce528a90d0b82afbed771fa920c7dbeafb6337135d4c",
        "public/js/player.js": "4ec34f94466e49fd6e1420dfe3794456314a8016df67d14939347a37b9ad8e59",
        "public/js/release-copy.js": "d72075a12d7661c14b5929aebabe52d99923fdc161552b773db1f4988b73d1d6",
        "public/js/runtime-config.js": "11a64acb75c9d27c74f3cb179c6b61390e30e742a62b19aa637dad63f0273622",
        "public/js/session-vault.js": "391394c144cda03c3741cc4dbc7a5e9a9f1c65fef42b6971394285252126f13d",
        "public/js/tv.js": "f292a93f903c5886548297f692fc543dc11285ade5226640baa1487d9c934221",
        "public/media/avengers_4k.jpg": "3a11f26e07395cd6e46150994ce7fb5791afe4e84e0dbdbaf15429a800f5b5a5",
        "public/media/killer_shop_4k.jpg": "cc85f3ae2bbab87c5c53d661b12b075e890705eb56bfb230d3f922ef07b500d6",
        "public/media/phim4k-avatar.png": "d642f4f713d22fb37651ecff7e47368ad03b79d8a9164732a2f2fef269e1e104",
        "public/media/poster-fallback.svg": "0dedb95cd60973a3677b66d330e80a20ece8c0752d6b2de178b5960bfd3a607f",
        "public/media/spider_man_4k.jpg": "1e6356bf1dfce786b534026aa48e9776a77090599380881a982fa1eaba7f79b0",
        "public/media/superman_4k.jpg": "9339c63a766caa26647be0b64cacf0c95e3db29859ce4445b5e9db15a05ab7fe",
        "public/media/the_boys_4k.jpg": "572cb16dfb429292bb9fc690a0c5bfa28a8d688ed23588595e396b454067971a",
        "public/vendor/hls.min.js": "afcde07437ec84b072fe8782e772ceb5046eac751b2719f73ae0d83d763bc3f5",
    ]

    static func verify(in bundle: Bundle = .main) -> Bool {
        guard let resourceRoot = bundle.resourceURL else { return false }
        let publicRoot = resourceRoot.appendingPathComponent("public", isDirectory: true)
        guard let enumerator = FileManager.default.enumerator(
            at: publicRoot,
            includingPropertiesForKeys: [.isRegularFileKey],
            options: [.skipsHiddenFiles]
        ) else { return false }

        var actualFiles = Set<String>()
        for case let url as URL in enumerator {
            guard (try? url.resourceValues(forKeys: [.isRegularFileKey]).isRegularFile) == true else { continue }
            let prefix = publicRoot.path + "/"
            guard url.path.hasPrefix(prefix) else { return false }
            let relative = "public/" + String(url.path.dropFirst(prefix.count))
            if relative.hasSuffix(".map") { return false }
            actualFiles.insert(relative)
        }

        guard actualFiles == Set(protectedFiles.keys) else { return false }
        for (relative, expectedDigest) in protectedFiles {
            let url = resourceRoot.appendingPathComponent(relative, isDirectory: false)
            guard let data = try? Data(contentsOf: url, options: .mappedIfSafe) else { return false }
            let digest = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
            guard digest == expectedDigest else { return false }
        }
        return true
    }
}
