// Generated by scripts/generate-ios-integrity-manifest.js. Do not edit manually.
import CryptoKit
import Foundation

enum RuntimeIntegrityManifest {
    private static let protectedFiles: [String: String] = [
        "public/cordova_plugins.js": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "public/cordova.js": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "public/css/modal.css": "266b60aa7525ae2d5f26a046cc631842f02709e0adb34f77db766496b7ac3f56",
        "public/css/player.css": "33ccca95d2151e408d8fc1684d9030680f85e4d371d4d262a3c761b21d6765c3",
        "public/css/style.css": "2a8783c4cb27e2855c273de6c7e1a5a8d99748e0236cc625caebcbf59a47097f",
        "public/css/tv.css": "71309558f2e7fb452d9abfa4906cbfc873df7acc407c7e4b7a411809b1629b0e",
        "public/index.html": "3a922c72d084ecf9394647be8390a3e449218f438c4242ed0a0e9453933c2a7b",
        "public/js/admin.js": "2978b4910b96604670b3d56bdb2b5d8f5853803f536b97d01b425a1e8c268b97",
        "public/js/api.js": "0f3b1f6ecbf5dc9f6ec45f5e97a66fce4c1dce27062cca2a8cf0dbfb34fca6d0",
        "public/js/app.js": "2d949bc5ee97589d52a8ec21abe85854826c3b5de216c459c366505a95e8d0ac",
        "public/js/audio-enhancer.js": "eb0d45f7f53135b5b787b1411aa58221506c84c895f1c8c1d6bebc262408dbce",
        "public/js/auth.js": "5a691b5e30844d8a6b9db4d3710ec0b7b6bb5b973fc6839ccbbf074cb2f35b8f",
        "public/js/catalog-fallback.js": "f583669da9767f8e816095616056592d67e2687e5d0a4f45193c0feaa8b4caf7",
        "public/js/coverflow.js": "d9ff2427b7319e6721b5b117ff3f28ef08a0121292c5e0b35e33ce4019bf3e83",
        "public/js/diagnostics.js": "d773c3786e3ca29c8c90f2b9b2703233bef341dc494ae6a95d3a4075c339b092",
        "public/js/home-curation.js": "cfebe7f3542b30254cb9f34feb77f66d807e94349570cbb678233e647063a5d2",
        "public/js/mobile-config.js": "abd21464170aaa51a999975fcc8ca89b0f22341e03c93797dba5623b89e5a424",
        "public/js/native-downloads.js": "b783c963d2636a2402e5d4823d9fe44b572e6f32fb2461bbe4705f840fa979f9",
        "public/js/platform.js": "aad0c655178247afce19bf30b31b7d2a02da99c09a807b4e3191e49ab8eb1160",
        "public/js/player-core.js": "9f0ed5ad98d42d7f1f1b211270f8d65075290c7afcbe135a6c2d0c2566265f86",
        "public/js/player.js": "59ce854ac6ab8460d6a0aca067c354e0522da2fb47f73af8f249c2a7d9f2e216",
        "public/js/runtime-config.js": "8d432390e94b695477092e578e575482f85965e80acc79569d3cfc0e2fb2e254",
        "public/js/tv.js": "2913eec5972696ba32039b530b62866223a9d95f668674c630f26a21d0dd8c42",
        "public/media/avengers_4k.jpg": "3a11f26e07395cd6e46150994ce7fb5791afe4e84e0dbdbaf15429a800f5b5a5",
        "public/media/killer_shop_4k.jpg": "cc85f3ae2bbab87c5c53d661b12b075e890705eb56bfb230d3f922ef07b500d6",
        "public/media/phim4k-avatar.png": "d642f4f713d22fb37651ecff7e47368ad03b79d8a9164732a2f2fef269e1e104",
        "public/media/poster-fallback.svg": "cd06825a934e2abde018910d90e04f4cd98b52c12034a8a42c2e9b0d4affe2cd",
        "public/media/spider_man_4k.jpg": "1e6356bf1dfce786b534026aa48e9776a77090599380881a982fa1eaba7f79b0",
        "public/media/superman_4k.jpg": "9339c63a766caa26647be0b64cacf0c95e3db29859ce4445b5e9db15a05ab7fe",
        "public/media/the_boys_4k.jpg": "572cb16dfb429292bb9fc690a0c5bfa28a8d688ed23588595e396b454067971a",
        "public/vendor/hls.min.js": "afcde07437ec84b072fe8782e772ceb5046eac751b2719f73ae0d83d763bc3f5",
    ]

    static func verify(in bundle: Bundle = .main) -> Bool {
        guard let resourceRoot = bundle.resourceURL else { return false }
        let publicRoot = resourceRoot.appendingPathComponent("public", isDirectory: true)
        guard let enumerator = FileManager.default.enumerator(
            at: publicRoot,
            includingPropertiesForKeys: [.isRegularFileKey],
            options: [.skipsHiddenFiles]
        ) else { return false }

        var actualFiles = Set<String>()
        for case let url as URL in enumerator {
            guard (try? url.resourceValues(forKeys: [.isRegularFileKey]).isRegularFile) == true else { continue }
            let prefix = publicRoot.path + "/"
            guard url.path.hasPrefix(prefix) else { return false }
            let relative = "public/" + String(url.path.dropFirst(prefix.count))
            if relative.hasSuffix(".map") { return false }
            actualFiles.insert(relative)
        }

        guard actualFiles == Set(protectedFiles.keys) else { return false }
        for (relative, expectedDigest) in protectedFiles {
            let url = resourceRoot.appendingPathComponent(relative, isDirectory: false)
            guard let data = try? Data(contentsOf: url, options: .mappedIfSafe) else { return false }
            let digest = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
            guard digest == expectedDigest else { return false }
        }
        return true
    }
}
